name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Snake
        uses: Platane/snk@master
        with:
          github_user_name: sriinathh  # replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
